# Generated by Django 2.0.5 on 2018-06-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowusertoken',
            name='subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
