# Generated by Django 2.0.5 on 2018-06-06 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20180606_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowusertoken',
            name='subscription_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
